// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOmOP3-lyj6p2U8ke3dYs7Fh2Q6IGy8o',
    appId: '1:101962090424:web:8f30605e5ae38688fb314d',
    messagingSenderId: '101962090424',
    projectId: 'homiesapp-ed572',
    authDomain: 'homiesapp-ed572.firebaseapp.com',
    storageBucket: 'homiesapp-ed572.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjXDEj73MaLme0bJ8hlzODLxkG7eml_s',
    appId: '1:101962090424:android:087ff325d2606694fb314d',
    messagingSenderId: '101962090424',
    projectId: 'homiesapp-ed572',
    storageBucket: 'homiesapp-ed572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4AAzJzQAg0oN9Fa5-NxFK1AgWXsybIbs',
    appId: '1:101962090424:ios:ee48cd1c837b80dbfb314d',
    messagingSenderId: '101962090424',
    projectId: 'homiesapp-ed572',
    storageBucket: 'homiesapp-ed572.firebasestorage.app',
    iosBundleId: 'com.example.homies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4AAzJzQAg0oN9Fa5-NxFK1AgWXsybIbs',
    appId: '1:101962090424:ios:ee48cd1c837b80dbfb314d',
    messagingSenderId: '101962090424',
    projectId: 'homiesapp-ed572',
    storageBucket: 'homiesapp-ed572.firebasestorage.app',
    iosBundleId: 'com.example.homies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtOmOP3-lyj6p2U8ke3dYs7Fh2Q6IGy8o',
    appId: '1:101962090424:web:d0469d622997f7e5fb314d',
    messagingSenderId: '101962090424',
    projectId: 'homiesapp-ed572',
    authDomain: 'homiesapp-ed572.firebaseapp.com',
    storageBucket: 'homiesapp-ed572.firebasestorage.app',
  );
}
